"""v4.0: Add message_cards and audit_logs tables

Revision ID: f84a99d62fad
Revises: d4c33985c815
Create Date: 2026-01-17 19:38:57.005128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f84a99d62fad'
down_revision: Union[str, None] = 'd4c33985c815'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('refund_application_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=False),
    sa.Column('decision_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_admin_id'), 'audit_logs', ['admin_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_order_id'), 'audit_logs', ['order_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_refund_application_id'), 'audit_logs', ['refund_application_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_risk_level'), 'audit_logs', ['risk_level'], unique=False)
    op.create_index(op.f('ix_audit_logs_thread_id'), 'audit_logs', ['thread_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('message_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('thread_id', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('sender_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=True),
    sa.Column('meta_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_cards_message_type'), 'message_cards', ['message_type'], unique=False)
    op.create_index(op.f('ix_message_cards_receiver_id'), 'message_cards', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_message_cards_sender_id'), 'message_cards', ['sender_id'], unique=False)
    op.create_index(op.f('ix_message_cards_status'), 'message_cards', ['status'], unique=False)
    op.create_index(op.f('ix_message_cards_thread_id'), 'message_cards', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_cards_thread_id'), table_name='message_cards')
    op.drop_index(op.f('ix_message_cards_status'), table_name='message_cards')
    op.drop_index(op.f('ix_message_cards_sender_id'), table_name='message_cards')
    op.drop_index(op.f('ix_message_cards_receiver_id'), table_name='message_cards')
    op.drop_index(op.f('ix_message_cards_message_type'), table_name='message_cards')
    op.drop_table('message_cards')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_thread_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_risk_level'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_refund_application_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_order_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_admin_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
